### ISSUE TITLE
[Bug] segmentation fault on listing the windows `t-rec -l`

### ISSUE THREAD

**Issue by ryuta69** [sassman/t-rec-rs#4]
**Describe the bug**
Whenever I run t-rec, it causes `segmentation fault` error. `t-rec /bin/sh` results same.

**To Reproduce**
1. Run `t-rec`.

**Expected behavior**
It doesn't cause segmentation fault, and run correctly.

**Screenshots**
<img width="574" alt="ss" src="https://user-images.githubusercontent.com/41639488/95670758-50184800-0bca-11eb-8785-3dbcbb9f99b9.png">

* Interestingly, as you see it leads error `zsh: error on TTY read: Input/output error` if you specified **zsh**, **bash**. However, **sh** won't lead this error.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Version: 10.15.7
 - Zsh: zsh 5.8 (x86_64-apple-darwin19.3.0)
 - sh: version 3.2.57(1)-release (x86_64-apple-darwin19)
 - bash: version 3.2.57(1)-release (x86_64-apple-darwin19)

**Additional context**

**Comment by sassman** [comment]
Could you please also share the graphics card on your mac? Like from "About this Mac" > "Displays"

**Comment by ryuta69** [comment]
@sassman 
Sure.

```
Displays: 
Built-in Display
2-inch (2304 x 1440)
Intel HD Graphics 615 1536 MB graphics
```

**Comment by sassman** [comment]
@ryuta69 thanks. Also maybe you can check for some headers on your system: `grep CGWindowListCopyWindowInfo /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/CoreGraphics.framework/Versions/Current/Headers/*.h`

And run `t-rec -l` and see if it lists you some windows with name and id. I suspect an issue with calling native osx core-graphics library functions on your system.

**Comment by ryuta69** [comment]
@sassman 
Sure


* headers on my system
```cpp
// /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/CoreGraphics.framework/Versions/Current/Headers/CGWindow.h

/* Return an array of window dictionaries for windows within the user
   session.

   This function returns NULL if the caller is not running within a Quartz
   GUI session or the window server is disabled. You should release the
   array when you are finished using it. */

CG_EXTERN CFArrayRef __nullable CGWindowListCopyWindowInfo(CGWindowListOption option,
    CGWindowID relativeToWindow)
    CG_AVAILABLE_STARTING(10.5);
```

* Run `t-rec -l`
```
zsh$ t-rec -l
Window | Id
zsh: illegal hardware instruction  t-rec -l

bash-3.2$ t-rec -l
Window | Id
Segmentation fault: 11

sh-3.2$ t-rec -l
Window | Id
Segmentation fault: 11
```

I'm afraid but I don't clearly get this means. But `Segmentation fault: 11` means Memory Access Error. Maybe it didn't get any window/id, so accessing empty...?

**Comment by sassman** [comment]
Very interesting, seems that is somehow graphics card related. But actually this whole crash should be prevented. So I will dig into that deeper.

One last thing I've noticed, when the mac screen recording permission are not granted, then the app also misbehaves, can you check that iTerm for example is authorized with a checkbox there:

![image](https://user-images.githubusercontent.com/329682/95679189-6c6bb300-0bd1-11eb-96f0-99737389851b.png)

**Comment by ryuta69** [comment]
Thank you for your researching, I also will look into.

> can you check that iTerm for example is authorized with a checkbox there

<img width="660" alt="ss" src="https://user-images.githubusercontent.com/41639488/95679507-43b5de80-0c0e-11eb-969b-58f9ffb6d386.png">

Right now, there is no checkbox for iTerm nor plus button to add iTerm. I believe this will show alert to permit when it requires (Maybe after segmentation fault is resolved...?)

**Comment by sassman** [comment]
> Right now, there is no checkbox for iTerm nor plus button to add iTerm. I believe this will show alert to permit when it requires (Maybe after segmentation fault is resolved...?)

On start there should be a pop up coming that requests you to allow the recoding by iTerm

Additionally, I committed a fix to the main branch, that should do more checks and give more output.
Maybe you can 

```
git clone https://github.com/sassman/t-rec-rs.git
cd t-rec-rs
cargo install -f --path .
```
and then redo a recording.

**Comment by ryuta69** [comment]
Thank you very much!
Oh, I'm afraid but is that fix commit not pushed yet...? (cloned and build, but it's same as before.)
https://github.com/sassman/t-rec-rs/commits/main

**Comment by ryuta69** [comment]
@sassman 
It fixes.
I now am going to send you PR.

**Comment by sassman** [comment]
> Oh, I'm afraid but is that fix commit not pushed yet...? (cloned and build, but it's same as before.)

Sorry pushed it as a wrong branch. Now you can try.

**Comment by ryuta69** [comment]
@sassman 
Thank you very much.

----

It will take time (maybe not possible to fix from rust code side) to create PR, so I describe why this error caused. 

First of all it was not because of graphic card.

The error was caused here.
```rust
    // src/macos/window_id.rs
    unsafe {
        CFRelease(window_list_info as CFTypeRef);
    }
```

Almost all application is fine with this, however, **Übersicht** does wrong.

<img width="576" alt="ss 6" src="https://user-images.githubusercontent.com/41639488/95681385-7b2a8800-0c1a-11eb-8020-e65f150e0d8c.png">

I think this is because of char code \u{308} does, because after I changed app name by editing info.plist of App, it works.

After I remove Übersicht and run correctly, this alert pops up.

> Right now, there is no checkbox for iTerm nor plus button to add iTerm. I believe this will show alert to permit when it requires

**Comment by sassman** [comment]
The umlaut "Ü" causes it. Very interesting. I will add some charset safety checks and also try to reproduce it. What app is it that is called "Übersicht" for you (maybe I can install it simply)?

**Comment by ryuta69** [comment]
Thank you for safety check proposal, I think it's a good idea.
This is the App.

Download: http://tracesof.net/uebersicht/
Github: https://github.com/felixhageloh/uebersicht

**Comment by sassman** [comment]
> Download: http://tracesof.net/uebersicht/ 

Thanks, I can directly reproduce the issue now.

**Comment by ryuta69** [comment]
Additional Info (If this is an obvious thing, sorry. I really don't know anything about MacOS CoreFoundation).

If I modify the code below,
https://github.com/sassman/t-rec-rs/blob/f65af3bdf9e8f0803b1bb0601c776d85a8c0c4a4/src/macos/window_id.rs#L26-L30

into below.
```
let window_list_info = unsafe {
    CGWindowListCopyWindowInfo(
            kCGWindowListOptionOnScreenOnly, kCGNullWindowID,
    )
};
```

Now, the error won't cause even with Übersicht. (OTOH, this makes functions `TERM_PROGRAM="google chrome" t-rec` disabled, so not right proposal. just additional info.)
<img width="644" alt="ss 9" src="https://user-images.githubusercontent.com/41639488/95682252-3fde8800-0c1f-11eb-8447-735afa13a19f.png">

---

I think I am too lack of understanding CoreFoundation, so will stop my own PR... Thank you for reviewing my report.

**Comment by sassman** [comment]
Thanks for all the details, I found the reason. The Objective C runtime took over the memory ownership, of an item that it does not own. So that caused on the `CFRelease` somehow a double free that lead to the seg fault. 

Can you please verify on the main branch if the problem is solved for you?

**Comment by sassman** [comment]
This fix is now included in v0.1.1 and published.

**Comment by ryuta69** [comment]
@sassman 
Yes, now it works with uebersicht!

Thank you very much for quick fix!

**Comment by sassman** [comment]
@ryuta69 thanks for your detailed feedback. The new version is just published on crates.io.
