### ISSUE TITLE
[FEAT] change `--bg` default to transparent

### ISSUE THREAD

**Issue by sassman** [sassman/t-rec-rs#46]
## Is your feature request related to a problem? Please describe.

Lot of sides where gif are embedded support meanwhile dark mode, so I would say it makes more sense to default the bg color to transparent. So that the white border is replaced by a transparent border.

**Comment by rijusougata13** [comment]
can you explain a little more.Where i have to make changes?

**Comment by sassman** [comment]
Sure: cli.es:38 it is

**Comment by sassman** [comment]
has been closed with PR #47. Thanks again.
