### ISSUE TITLE
command line parameter to control pre/post pause

### ISSUE THREAD

**Issue by sassman** [sassman/t-rec-rs#68]
## context

- sometimes at the end of a gif there needs to be a pause, in order to calm down, and not get a crazy fast spinning back dizziness. 
- Also on the other hand before things get to the point too fast, it can be beneficial to have a little grace time where the user would see the first frame for seconds before the animation / video would start.

## proposal

1. a `--end-pause | -e` to specify the post / end pause time, that is the time in seconds that the gif / video will show the last frame.
2. a `--start-pause | -s` to specify the pre / start pause time, that is the time in seconds that the first frame will be shown

## suggested by
@Hoverbear [on twitter](https://twitter.com/a_hoverbear/status/1389581526598184961)

**Comment by sassman** [comment]
/to @Hoverbear 
do you think that full seconds might be enough? Or better going for milli seconds?

<img width="848" alt="image" src="https://user-images.githubusercontent.com/329682/117205459-f25f7d80-adf1-11eb-9d55-0e819e6db529.png">

**Comment by Hoverbear** [comment]
Wonder if you could use humantime to let it be flexible? https://docs.rs/humantime/2.1.0/humantime/

**Comment by sassman** [comment]
great idea!
