### ISSUE TITLE
command line parameter for video only

### ISSUE THREAD

**Issue by sassman** [sassman/t-rec-rs#71]
**Is your feature request related to a problem? Please describe.**
Right now the parameter `-m | --video` would produce a gif and a mp4 file, while omitted only a `gif` would be produced. 

it would be cool to have a `--only-video` flag that would make the video as `-m` but skip the gif. 

Mentioned by @Hoverbear [on twitter](https://twitter.com/a_hoverbear/status/1389579539999715332)

**Comment by Hoverbear** [comment]
Nice job!!!
